-- RotaScan — Seed inicial: 105 bairros de Jataí/GO
-- Idempotente: ON CONFLICT DO NOTHING garante reexecução sem duplicatas

DO $$
DECLARE
  v_cidade_id UUID;
BEGIN
  INSERT INTO cidades (nome, uf)
  VALUES ('Jataí', 'GO')
  ON CONFLICT (nome, uf) DO NOTHING;

  SELECT id INTO v_cidade_id FROM cidades WHERE nome = 'Jataí' AND uf = 'GO';

  INSERT INTO bairros (cidade_id, nome)
  VALUES
    (v_cidade_id, 'Aimbiré'),
    (v_cidade_id, 'Área Rural de Jataí'),
    (v_cidade_id, 'Bela Vista'),
    (v_cidade_id, 'Bela Vista II'),
    (v_cidade_id, 'Centro'),
    (v_cidade_id, 'Cohacol 1'),
    (v_cidade_id, 'Colméia Park'),
    (v_cidade_id, 'Conjunto Cidade Jardim II'),
    (v_cidade_id, 'Conjunto Dorival de Carvalho'),
    (v_cidade_id, 'Conjunto Filostro Machado'),
    (v_cidade_id, 'Conjunto Residencial Cidade Jardim'),
    (v_cidade_id, 'Conjunto Residencial Mauro Antônio Bento'),
    (v_cidade_id, 'Conjunto Residencial Nossa Senhora de Fátima'),
    (v_cidade_id, 'Conjunto Rio Claro I'),
    (v_cidade_id, 'Conjunto Rio Claro II'),
    (v_cidade_id, 'Conjunto Rio Claro III'),
    (v_cidade_id, 'Conjunto Sebastião Herculano de Souza'),
    (v_cidade_id, 'Distrito Agroindustrial'),
    (v_cidade_id, 'Divino Espírito Santo'),
    (v_cidade_id, 'Dom Abel'),
    (v_cidade_id, 'Dom Benedito D. Coscia'),
    (v_cidade_id, 'Fernandes'),
    (v_cidade_id, 'Hamilton Nunes'),
    (v_cidade_id, 'Jardim da Liberdade'),
    (v_cidade_id, 'Jardim Floresta'),
    (v_cidade_id, 'Jardim Paraíso'),
    (v_cidade_id, 'Jardim Primavera'),
    (v_cidade_id, 'José Estevam'),
    (v_cidade_id, 'José Ferreira'),
    (v_cidade_id, 'Loteamento Carvalho'),
    (v_cidade_id, 'Loteamento João Rodrigues da Cunha'),
    (v_cidade_id, 'Loteamento Santa Rosa'),
    (v_cidade_id, 'Popular'),
    (v_cidade_id, 'Primavera II'),
    (v_cidade_id, 'Recanto Alvorada - Sítios de Recreio'),
    (v_cidade_id, 'Residencial Bandeirantes'),
    (v_cidade_id, 'Residencial Barcelona'),
    (v_cidade_id, 'Residencial Cohacol 5'),
    (v_cidade_id, 'Residencial Cylleneo França'),
    (v_cidade_id, 'Residencial das Abelhas'),
    (v_cidade_id, 'Residencial das Brisas'),
    (v_cidade_id, 'Residencial das Brisas II'),
    (v_cidade_id, 'Residencial Eldorado'),
    (v_cidade_id, 'Residencial Flamboyant'),
    (v_cidade_id, 'Residencial Jardim dos Ipês'),
    (v_cidade_id, 'Residencial Jardim Jataí'),
    (v_cidade_id, 'Residencial Morada do Sol'),
    (v_cidade_id, 'Residencial Parque dos Ventos'),
    (v_cidade_id, 'Residencial Portal do Sol - 1ª Etapa'),
    (v_cidade_id, 'Residencial Portal do Sol - 2ª Etapa'),
    (v_cidade_id, 'Residencial Recanto da Mata'),
    (v_cidade_id, 'Residencial Setor Sul'),
    (v_cidade_id, 'Residencial Terras de Toscana'),
    (v_cidade_id, 'Samuel Grahan'),
    (v_cidade_id, 'Santa Lúcia'),
    (v_cidade_id, 'Santa Lúcia II'),
    (v_cidade_id, 'Santa Terezinha'),
    (v_cidade_id, 'Santo Antônio'),
    (v_cidade_id, 'Sebastião Herculano I'),
    (v_cidade_id, 'Serra Azul'),
    (v_cidade_id, 'Setor Aeroporto'),
    (v_cidade_id, 'Setor Alto das Rosas'),
    (v_cidade_id, 'Setor Antena'),
    (v_cidade_id, 'Setor Brasília'),
    (v_cidade_id, 'Setor Central - Parte Baixa'),
    (v_cidade_id, 'Setor Colinas'),
    (v_cidade_id, 'Setor Cordeiro'),
    (v_cidade_id, 'Setor das Mansões'),
    (v_cidade_id, 'Setor Epaminondas I'),
    (v_cidade_id, 'Setor Epaminondas II'),
    (v_cidade_id, 'Setor Estrela Dalva'),
    (v_cidade_id, 'Setor Fabriny'),
    (v_cidade_id, 'Setor Francisco Antônio'),
    (v_cidade_id, 'Setor Geda'),
    (v_cidade_id, 'Setor Granjeiro'),
    (v_cidade_id, 'Setor Hermosa'),
    (v_cidade_id, 'Setor Industrial'),
    (v_cidade_id, 'Setor Iracema'),
    (v_cidade_id, 'Setor Jacutinga'),
    (v_cidade_id, 'Setor Jardim Goiás'),
    (v_cidade_id, 'Setor Jardim Goiás II'),
    (v_cidade_id, 'Setor José Bento'),
    (v_cidade_id, 'Setor Oeste'),
    (v_cidade_id, 'Setor Planalto'),
    (v_cidade_id, 'Sítios de Recreio Alvorada'),
    (v_cidade_id, 'Sodré'),
    (v_cidade_id, 'Vila Campo Neutro'),
    (v_cidade_id, 'Vila Carla'),
    (v_cidade_id, 'Vila das Palmeiras'),
    (v_cidade_id, 'Vila Fátima'),
    (v_cidade_id, 'Vila Frei Domingos'),
    (v_cidade_id, 'Vila Jardim América'),
    (v_cidade_id, 'Vila Jardim Maximiano Peres'),
    (v_cidade_id, 'Vila Jardim Rio Claro'),
    (v_cidade_id, 'Vila Luíza'),
    (v_cidade_id, 'Vila Mutirão'),
    (v_cidade_id, 'Vila Nossa Senhora do Carmo'),
    (v_cidade_id, 'Vila Olavo'),
    (v_cidade_id, 'Vila Paraíso I'),
    (v_cidade_id, 'Vila Paraíso II'),
    (v_cidade_id, 'Vila Progresso'),
    (v_cidade_id, 'Vila Santa Maria'),
    (v_cidade_id, 'Vila São Pedro'),
    (v_cidade_id, 'Vila Sofia'),
    (v_cidade_id, 'Vila Três Marias')
  ON CONFLICT (cidade_id, nome) DO NOTHING;
END;
$$;
